default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: instagram_development
  username: lewis
  password: Pr3s3ntthem

test:
  <<: *default
  database: instagram_test
  username: lewis
  password: Pr3s3ntthem

production:
  <<: *default
  database: guestbook_production
  username: lewis
  password: Pr3s3ntthem
